<!-- break -->
<br>
<!-- break -->

I view my relationship with students and postdocs as a partnership. My job is to ensure people in the lab get the training and opportunities they need to advance in their chosen careers, whether in academia, industry, teaching, or other options. Below you can find information on the lab philosophy and expectations of lab members. Text and ideas in places borrow heavily from [Rubén Rellán-Álvarez](http://www.rrlab.org/expectations.html).

## General Rules

### Safety first

Your health and safety are more important than your research. This includes adhering to lab safety codes, as well as maintaining your physical and mental health. Never work in the lab if you are feeling sick, under medication that might affect your ability to work normally and definitely not under the effects of any kind of drugs. Avoid working in the lab by yourself doing potentially dangerous activities, and please be aware of UC Davis resources and training on [lab safety](http://safetyservices.ucdavis.edu/categories/laboratory-safety). 

### Respect

I expect lab members to contribute to a productive and friendly environment conducive to learning and research. This includes treating your colleagues with respect, listening to others’ viewpoints and ideas, and ensuring the lab is a place where everybody feels welcome and appreciated. Racist, sexist, or other inappropriate comments or behavior will not be tolerated under any circumstance.  The university provides a number of [resources](http://studentexpression.ucdavis.edu/get-support/index.html) (confidential and otherwise) to report or discuss any such activity you feel is inappropriate.

### Expectations (for all members)

#### Work hours
We are lucky enough to work in an area where flexible working hours are the norm. In order to be able to interact with the rest of the persons in the lab, we generally expect lab members to be present the majority of normal business hours (9-5pm) during the work week, since this is when most academic activities occur. There may be times when your project requires work late at night or on the weekends, but you are *not* expected to regularly work more than a normal 40-hour work week.  It is important that you take time off for personal life, vacations, etc.  I do ask, however, that you notify me if you will be absent for ≥1 day, and let me know in advance of any extended leave.

#### Seminars, journal clubs and other lab and institutional activities   
Attendance to regular weekly lab meetings is expected of all lab members. Participation in weekly lab coffee, Zeavolution and other regular meetings, and [R.E.H.A.B.](rehab.html) is encouraged but not required. Note that if you are funded on one of the lab's current grants, you are expected to attend those meetings as well.  There are a number of seminars (Plant Biology, Genetics, Population Biology, Ecology & Evolution, Plant Sciences) each week, and these are usually posted in the office. You are  strongly encouraged to regularly go to one or more each week.

#### Conferences
Everyone is encouraged to attend at least one conference a year.  Members of the lab regularly attend such meetings as the maize meeting, SMBE, Evolution, and ESA. The department and university offer travel funding for graduate students and postdocs, and you should apply for external sources of funding to help cover travel expenses. Whenever possible, I will help fund attendance at one conference per year for each member of the lab on the condition that you are presenting a poster or talk at the meeting. Please provide ample time before the deadline for reviewing abstracts and posters or practicing talks. 

#### Authorship
We follow the [IJME rules for authorship rules](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html):   
1. Substantial contributions to the conception or design of the work; or the acquisition, analysis, or interpretation of data for the work; AND  
2. Drafting the work or revising it critically for important intellectual content; AND  
3. Final approval of the version to be published; AND  
4. Agreement to be accountable for all aspects of the work in ensuring that questions related to the accuracy or integrity of any part of the work are appropriately investigated and resolved.
Projects evolve over time and authorship inclusion and author order will be re-evaluated accordingly.

#### Open Science
I feel strongly that open science is important. We write papers on github or [overleaf](overleaf.com), often in public repos.  We publish preprints as soon as a manuscript is ready for submission.  We publish our data as soon as we can, and I am pushing to start doing so as separate data papers. We document our work -- with github, R markdown, readme files, etc. -- so it is intelligible and reusable in the future. I expect members of the lab to practice open science.


## Specific rules for the different members of the lab

### Postdocs and senior PhD students  

#### My responsibilities to postdocs and senior PhD students:  

- Assist with identifying and writing postdoctoral fellowships.  
- Develop project ideas, including independent projects that can be taken with the postdoc.
- Interpret results.
- Proof-read manuscripts.
- Discuss future career goals (e.g., do you want to teach, go into academia, industry, continue in research?), and plan ways to facilitate these goals.
- Meet weekly to discuss progress & pitfalls.  

#### Expectations of postdocs and senior PhD students:
- Prepare for our regular progress/pitfalls meetings and a follow up email of progress and goals.  
- Write and submit manuscripts.  I strongly encourage collaboration, and a quick glance at our [publications](pubs.html) should show that this generally works well. On average I expect your time as a postdoc in the lab to generate ~2 papers per year (first or co-authored), and in general this expectation seems to be not unreasonable.
- Proof-read manuscripts from other lab members.  
- Apply for external funding (either individual postdoc fellowships or contributing to larger lab grant writing).  
- Maintain a set of lab notes, including directories of data, annotated codes & versions, detailed methods. These need to sufficient to reproduce results without additional instructions. A good working example can be found [here](https://github.com/timbeissinger/Maize-Teo-Scripts).
- Participate in general lab responsibilities (servers, maintain common areas, taking turns hosting visitors). Participate in talk rehearsals of your colleagues.
- Optional, but encouraged: Mentor at least one undergraduate student.

### Master and junior PhD students

#### My responsibilities to Master and junior PhD students:

- Develop project ideas.   
- Interpret results.  
- Proof-read and contribute to writing of thesis, abstracts and  manuscripts.  
- Discuss future career goals (e.g., do you want to teach, go into academia, continue in research?), and plan ways to facilitate these goals.  
- Meet weekly to discuss progress and pitfalls.

#### Expectations of Master and junior PhD students:  

- Prepare for our regular progress/pitfalls meetings and a follow up email of progress and goals.  
 - Write and submit manuscripts.  On average, I expect most students to produce three publications over the course of their PhD, including at least one first-author paper. 
- Maintain a set of lab notes, including directories of data, annotated codes & versions, detailed methods. These need to sufficient to reproduce results without additional instructions. A good working example can be found [here](https://github.com/timbeissinger/Maize-Teo-Scripts).
- Write thesis in due time.  
- Proof-read manuscripts from other lab members. Participate in talk rehearsals of your colleagues.  
- Participate in general lab responsibilities (servers, maintain common areas, taking turns hosting visitors, communal sampling and field work etc). Participate in talk rehearsals of your colleagues.  
- Present multiple research talks/posters at conferences over the course of your time in the lab. You are encouraged to do so annually, but this isn't always possible.
- Optional, but encouraged: Mentor at least one undergraduate student.
