---
title: "Lab Manager"
---

We are seeking to hire a motivated and and collaborative lab manager to keep the lab running smoothly.

##### Duties and Responsibilities: 
The succesful candidate will oversee day-to-day operations of the lab including maintenance, compliance with safety regulations, and training.  They  
will be directly involved in multiple aspects of lab research from experimental design to carrying out experiments in the lab, greenhouse and field. Finally, the candidate will also act as project manager for our [HiLo project](http://highlandadaptation.org), assisting with travel, meeting organization, project reports, and presentations.
Although no experience with data analysis is required, the lab provides an excellent environment to learn such skills, and involvement in analysis and publication is strongly encouraged -- our previous lab manager authored [multiple papers](https://scholar.google.com/citations?user=mnHb3lYAAAAJ&hl=en) during her time in the lab. 

##### Minimum qualifications: 
B.S. in a biological field. Good communication and critical thinking skills. Hands-on laboratory experience. Excellent organizational and communication skills and the ability to maintain a detailed and accurate research lab notebook. Ability to work independently and also to develop effective working relationships with students, faculty and staff as part of a team environment.  Familiar with basic molecular biological techniques.

##### Preferred qualifications: 
M.S. in a biological field. Lab management experience. Experience with: maize or other plants, greenhouse and field work, library preparation for sequencing. Knowledge of genetics, evolutionary biology, molecular biology, statistics, and basic computational biology a plus.

##### Salary and job details: 
\$39,500 - $49,700 annually with full benefits, depending on experience. This is a 12-month term appointment with the possibility of extension contingent on successful performance and continued funding. The Ross-Ibarra lab is committed to ensuring a safe, friendly, and inclusive workplace for all its members, regardless of nationality, race or ethnicity, gender, religion, sexual orientation, age, or medical conditions. We especially encourage applications from persons traditionally underrepresented in the sciences.

##### To apply
The official ad will be posted soon at the UCD job site; check here for updates. To inquire please submit (1) a cover letter with a brief description of your experience and career goals, (2) a CV, and (3) a list of three people that we can contact as professional references. 
