<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5300959-3', 'auto');
  ga('send', 'pageview');

</script>

## News

### July
• The lab has a new home in [EVE](http://eve.ucdavis.edu) and will be moving to Storer Hall!

### June
• Dianne Velasco and Michelle Stitzer [walk at graduation](images/IMG_1750.jpg)! 
• [Dan Gates](*https://www.youtube.com/watch?v=AIR837EjcIE) and [Michelle Stiter](https://www.youtube.com/watch?v=lkZ_tDSoMe8) give talks at the Evolution conference. Michelle wins the [WD Hamilton Award](https://www.evolutionsociety.org/content/society-awards-and-prizes/the-w-d-hamilton-award.html) for outstanding student presentation!
• Elli wins a computational biology fellowship for summer 2019.

### April 
• Silas Tittes joins the lab to work on  [PanAnd](https://panandropogoneae.com).
• Li Wang leaves the lab to start her new job later this summer the the [Agricultural Genomics Institute](http://agis.caas.cn/en/index.htm) in Shenzhen.
• Sarah O, Elli, and Alyssa all get scholarships to attend the [Summer Institute of Statistical Genetics](https://www.biostat.washington.edu/suminst/sisg) in Seattle.
• Elli wins a Dept. of Plant Sciences graduate student research fellowship.

### March
• Markus Stetter starts his [new lab](https://www.cropevolution.org/index.html) at the University of Cologne.
• Elli Cryan joins the lab, coadvised by [Dan Kliebenstein](https://psfaculty.plantsciences.ucdavis.edu/kliebenstein/) to work on network evolution.

### February
• Wenbin Mei leaves to start a new job at [Inari Ag](https://www.inari.com).

### Januray
• Emily Josephs starts her [new lab](https://josephslab.github.io) at Michigan State. 

##2018

### October
Alyssa Phillips joins the lab to work on the [PanAnd](https://panandropogoneae.com) project.

### May 
• RILAB at PEQG. Emily Josephs and Michelle Stitzer talking, Dan Gates, Wenbin Mei, Ellen Osborn, Markus Stetter, presenting posters, as well as collabroators Raul Torres and Erin Calfee.
• Skype-a-scientist with [8th graders at Denville](https://twitter.com/VV_GoGreen/status/994647441948512256)
• Michelle wins a 3rd year of [ARCS](https://drewaltizer.com/event/11169-2018-arcs-symposium-advancing-science-in-america/photo/3918446-michelle_stitzer) support!

### April  
• Sarah and Asher both win departmental fellowships, supporting ~40% of their PhD for the next 4 years. Congrats!
• Congrats to Asher for winning an NSF Graduate Research Fellowship to work on biotic interactions in teosinte. 

### March   
• Anne [defends her PhD](images/anne_phd.jpg) 
• Jeff [gives a plenary talk](images/jri_mgc18.jpeg) at the Maize Genetics Conference

### Jan 
• Luis starts a new job at [HM Clause](http://hmclause.com).  
• JRI (slides [here](https://www.slideshare.net/jrossibarra/parallel-altitudinal-clines-reveal-adaptive-evolution-of-genome-size-in-zea-mays) and [here](https://www.slideshare.net/jrossibarra/adaptation-in-plant-genomes-bigger-is-different)), Emily, and [Michelle](https://twitter.com/GrameneDatabase/status/953383803875033088) all speak at PAG. 

##2017

### Nov 4  
Michele [talks at BAPG](https://twitter.com/pleunipennings/status/926885771306450944).

### Oct 13
JRI speaks at [CU Boulder](https://www.colorado.edu/ebio/) on [intraspecific](http://www.biorxiv.org/content/early/2017/07/13/134528) and [interspecific](https://www.biorxiv.org/content/early/2017/10/02/196501) work on genome size and adaptation. [Slides online](https://www.slideshare.net/jrossibarra/genome-size-and-adaptation-in-plants) too.  

### Sept 27
Our first lab R package! Luis and Mike May working together to put a Baysian [clustering method](https://cran.r-project.org/web/packages/DPP/index.html) together.

### Sept 20
Anna finishes her PhD!  Dr. O'Brien leaves the lab for a postdoctoral position at U. Toronto with [Megan Frederickson](http://mutualism.ca/).

### Sep 18
Markus receives news of a 2-year postdoc fellowship from the [DFG](http://www.dfg.de/en/). He'll be working on population and quantitative genetic approaches to studying domestication.

### July 31
Jinliang leaves the lab to start his [own lab](http://jyanglab.com) at the University of Nebraska. Sad to see him go, but proud and excited to see what he'll be up to!

### July 13
Caryn's Jastro proposal to investigate convergent evolution and DMI in highland maize is funded.

### June 1
Michelle awarded a summer GSR position in computation biology. 

### May 10
Michelle wins a prestigious [ARCS](https://northern-california.arcsfoundation.org) scholarship!

### May 9
Michelle presents at the [U. Georgia plant breeding symposium](http://plantsymposium.uga.edu/speakers/2_speaker_stitzer/).

### Mar. 27 
Simon's paper on [subgenomes of maize](http://biorxiv.org/content/early/2016/12/19/095547) accepted for publication in MBE

### Mar. 20
Caryn and Ellen both receive fellowships to attend the [summer institute for statistical genetics](https://www.biostat.washington.edu/suminst/sisg).  

### Feb. 20
[Caryn Johansen](https://twitter.com/jo_caryn) joins the lab, to be co-advised by the inimitable [Dan Runcie](http://runcielab.ucdavis.edu).

### Jan 10
Jeff starts as Senior Editor for popgen at [G3](http://www.g3journal.org).

##2016

### Dec. 8
Kevin Boardman awarded prestigious [Provost's Undergraduate Fellowship](http://urc.ucdavis.edu/awards/puf/)!

### Nov. 25
NSF proposal bounces; good reviews and feedback from PO.  Will retool and resubmit.

### Aug 10
[JRI presents](https://twitter.com/grmunjal/status/763549906363486208) on corn origins and diversity at the [Davis Science Cafe](https://capscicomm.org/local-science-cafes/davis-science-cafe/)

### June 1
Wenbin Mei starts as new postdoc in the lab to look at structural variation in maize and teosinte.

### May 5
Michelle Stitzer wins prestigious [ARCS](https://www.arcsfoundation.org) fellowship!

### May 3
NSF preproposal with Yaniv Brandvain invited for full proposal.

### April 10
Simon Renny-Byfield is off for a job at Dupont Pioneer, working in the same group as lab collaborators Justin Gerke and Eli Rodgers-Melnick. A sweet gig!

### March 25
JRI receives official word on promotion to full professor!

### March 16
JRI wins Mid-Career Award for Excellence in Maize Genetics at the Maize Genetics Conference in Florida.

### Feb 10
Josh Hough begins as new postdoc in the lab, to work on linked selection in teosinte.

##2015

### September 18

[Kate Crosby](https://github.com/kate-crosby) leaves the lab this month for her job in the Monsanto [Emerging Leaders Program](http://www.monsanto.com/careers/pages/emerging-leaders-in-science.aspx).  

### August 20

[Tim Beissinger](http://beissingerlab.github.io) leaves to take up his new job as USDA-ARS Research Geneticist at Missouri, filling the vacancy left when our collaborator Mike McMullen retired.

### June 26

Two grants funded today!  Funding from [UCMEXUS](http://ucmexus.ucr.edu) to work with [Ruairidh Sawers](http://www.langebio.cinvestav.mx/?pag=165) on characterizing an adaptive inversion introgression from teosinte into maize. And funding from the [UC-Mexico Initiative](http://ucmexicoinitiative.ucr.edu) (yup, they are different things!) to work on characterizing changes in genetic diversity and climate adaptation in maize over time using [CIMMYT SeeD](http://www.cimmyt.org/en/where-we-work/global-activities/seeds-of-discovery) data.

### June 9
After a bit less than a year in the lab, [Tim Beissinger](http://timbeissinger.github.io) accepts a job as a research scientist at USDA at the University of Missourri. This is [Mike McMullen's](http://www.ars.usda.gov/pandp/people/people.htm?personid=3766) position, so some big shoes to fill.  Congrats Tim!

### Mar. 17
Paul Bilinski is awarded a  UC Davis Dissertation Year Fellowship.  Congrats Paul!

### Mar. 9
The new [maize diversity website](www.panzea.org) is live!

### Jan. 28
Paul Bilinski is chosen to present his work on repeat evolution at the [SMBE Satellite meeting](http://smbeba2015.imag.fr) in Montepllier. Both SMBE and the Dept. of Plant Sciences have agreed to fund his trip!

### Jan. 9
Preprint of Shohei's paper on convergent evolution in the highlands is up on [bioRxiv](http://biorxiv.org/content/early/2015/01/09/013607), and Michelle's work on identifying new TEs as collaboration with [Nathan Springer's group](http://www.cbs.umn.edu/lab/springer) is out at [PLoS Genetics](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.1004915)!

### Jan. 8
Our collaboration with [Rute Fonseca](http://rutefonseca.wix.com/bioinformatics), [Bruce Smith](http://anthropology.si.edu/archaeobio/smith.html), and [Tom Gilbert](http://geogenetics.ku.dk/research_groups/gilbert_groups/) analyzing ancient maize in the US SW is out in [Nature Plants](http://www.nature.com/articles/nplants20143), with a nice both in [Nature Plants commentary](http://www.nature.com/articles/nplants20149) and a highlight in [Science](http://news.sciencemag.org/archaeology/2015/01/how-corn-became-corn) and a [press release](http://news.ucdavis.edu/search/news_detail.lasso?id=11124) by UC Davis.

### Jan. 6

Smithsonian funds our grant with [Dolores Piperno](http://en.wikipedia.org/wiki/Dolores_Piperno) and [Matt Hufford](http://www.public.iastate.edu/~mhufford/HuffordLab/home.html) entitled "Phenotypes, Environmental Plasticity, and Gene Expression in Teosinte and Maize in Ancient Climates Before and During the Time of Domestication".

##2014

### Dec. 15

Our Plant Genome grant was declined by NSF, but with constructive reviews. You can see reviews and proposal on [github](https://github.com/RILAB/PGRP).

### Dec. 12

Michelle Stitzer awarded a [Global Food Initiative Fellowship](http://www.universityofcalifornia.edu/press-room/dozens-uc-students-awarded-global-food-initiative-fellowships) for her work on the maize genome

### Dec. 11

Jeff [joins G3](http://genestogenomes.org/?p=658&preview=1&_ppp=ce3cb6a6ec) as an Associate Editor.

### Nov 21

Added an [interview](http://www.rilab.org/attachments/attachments/vanHeerwaarden_2011.m4a) on our [2011 paper](http://www.pnas.org/content/108/3/1088.long) on the geography of maize domestication.

### Nov 7

Added an [interview](http://www.rilab.org/attachments/Hufford_et_al._12_Nature_Genetics.m4a) with [Matt Hufford](http://www.public.iastate.edu/~mhufford/HuffordLab/home.html) on his 2012 [maize domestication paper](http://www.nature.com/ng/journal/v44/n7/full/ng.2309.html).

### Nov 3

Nice [perspective piece](http://www.nature.com/nature/journal/v514/n7524_supp/full/514S58a.html) on rice domestication in Nature, including comment from Jeff on debating one vs two domestications.

### Nov 1

Nice [interview](http://www.peoplebehindthescience.com/dr-norman-ellstrand/) with my MS adviser Norm Ellstrand, including a kind reference to the RILAB as one of his "new mentors".

### Oct 27

Kate Crosby arrives, bringing the lab to a quintessential quintet of quality postdocs. Also, Jeff signs on to be an Associate Editor at [G3](http://www.g3journal.org).

### Oct 24

UCD [mentions lab work on adaptation](http://ucdavismagazine.ucdavis.edu/issues/fall14/hot_crops.html).  

### Oct 12, 2014

Jeff is quoted in a [story at The Scientist](http://www.the-scientist.com/?articles.view/articleNo/41194/title/360-Degree-View-of-the-Tomato/) on the recent [tomato resequencing paper](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3117.html).

### Oct 10, 2014

Local adaptation review with [Peter Tiffin](http://www.cbs.umn.edu/lab/tiffin) accepted at Trends in Ecology and Evolution. See the [preprint](https://peerj.com/preprints/488/) here.

### Oct 1, 2014

Sadly, Vince Buffalo leaves the lab for a PhD in [Graham Coop's lab](www.gcbias.org). On a happy note, Jinliang Yang joins the group to do a postdoc on maize quantitative genetics! Good luck Vince, and welcome Jinliang!

### Sept 17, 2014

Rute Fonseca's paper on ancient maize DNA in the US Southwest was accepted at Nature Plants!

### Aug 15, 2014

Our new preprint on TEs and gene expression, a collaboration with the [Springer Lab](http://www.cbs.umn.edu/lab/springer), is no on bioRxiv(http://biorxiv.org/content/early/2014/08/15/008052). Features some great work by Michelle Stitzer identifying novel TE insertions.

### Aug 10, 2014

Paul Bilinksi's paper on centromere repeats in the maize genome is accepted in Chromosoma!

### Aug 4, 2014

Submitted an [NSF proposal](https://github.com/HuffordLab/NSF_DEB) with [Matt Hufford](http://www.public.iastate.edu/~mhufford/HuffordLab/home.html) on hybridization in *Zea*. Fingers crossed!

### July 2, 2014

Our NSF Catalyzing New International Collaborations grant with [Matt Hufford](http://www.public.iastate.edu/~mhufford/HuffordLab/home.html), [Angelica Cibrian-Jaramillo](http://www.langebio.cinvestav.mx/?pag=426), [Graham Coop](www.gcbias.org), [Sherry Flint-Garcia](http://web.missouri.edu/~flint-garcias/home.html), and [Ruairidh Sawers](http://www.langebio.cinvestav.mx/?pag=165) was funded. Off to Mexico!

### June 17, 2014

Michelle Stitzer is awarded a Jastro research grant for her work on nonautonomous TEs.

### June 16, 2014

Michelle Stitzer passes her first-year population biology comprehensive exam. Woot!

### June 5, 2014

Paul Bilinski awarded a summer GSR position in computation biology. Congrats Paul!

### June 2, 2014

Our paper on tb1 in natural populations of teosinte submitted and online as [preprint](http://biorxiv.org/content/early/2014/06/03/005819).

### May 16, 2014

Jeff has been admitted officially to the [Ecology Graduate Group](http://ecology.ucdavis.edu)!

### May 13, 2014

Happy to announce [Simon Renny-Byfield](http://webspace.qmul.ac.uk/sbyfield/Simon_Renny-Byfield/Welcome.html) will be joining the lab as a postdoc for Fall 2014 to work on our rare alleles project.

### May 12, 2014

Paul Bilinski's first dissertation chapter, submitted for publication and now online as a [preprint](http://biorxiv.org/content/early/2014/05/12/005058). Congrats Paul!

Future R-I Lab postdoc Tim Beissinger succesfully defended his PhD thesis today. Congrats Tim!

### May 8, 2014

[Awesome corn goodies](http://www.rilab.org/images/cornsticks.jpg) mysteriously show up in the lab, coincidentally timed perfectly with Jeff's absence.

### May 1, 2014

Our recently submitted NSF proposal on highland adaptation to the Plant Genome program. With [Matt Hufford](http://www.public.iastate.edu/~mhufford/HuffordLab/home.html), [Sherry Flint-Garcia](http://web.missouri.edu/~flint-garcias/), [Graham Coop](http://gcbias.org/), [Ruairidh Sawers](http://www.langebio.cinvestav.mx/?pag=165), and [Angelica Cibrian](http://www.langebio.cinvestav.mx/?pag=426).

### Apr 28, 2014

RILAB student Nivaz Brar presents [a poster](http://www.rilab.org/images/nivaz.jpg) on her hunt for an embryo lethal TE insertion in maize at the [UC Davis Undergraduate Research Conference](http://undergraduateresearch.ucdavis.edu/urcConf/).

### Apr 25, 2014

Reacting to an [urgent call for bioinformatics acronyms](http://www.acgt.me/blog/2014/4/25/acgttgca-has-every-possible-dna-based-initialism-been-used-by-the-bioinformatics/genomics-community?utm_content=bufferd1dd5&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer), [Matt Hufford](http://www.public.iastate.edu/~mhufford/HuffordLab/home.html) and I are proud to announce the formation of the Corn Transcriptome Analysis Group, or CTAG. Because we have some RNA-seq data and can run [EdgeR](http://www.bioconductor.org/packages/release/bioc/html/edgeR.html), that's why.

### Apr. 4, 2014

Congratulations to Anna O'Brien for being awarded a three year Plant Sciences graduate student research assistantship!

### Mar. 20, 2014

A fond au revoir to [Dr. Sofiane Mezmouk](http://www.linkedin.com/pub/sofiane-mezmouk/6b/a35/a34), who leaves the lab for a position as a research scientist at [KWS](http://www.kws.de/ca/fh/thd/).

### Feb. 26, 2014

[Video](http://tinyurl.com/esebvideo/?id=Dbj4Lv4QXlo) of [Tanja Pyhäjärvi](https://wiki.oulu.fi/pages/viewpage.action?pageId=13382392) presenting a seminar on her [postdoc work](http://gbe.oxfordjournals.org/content/5/9/1594) in the lab at ESEB.

### Feb. 5, 2014

My seminar [slides](http://www.slideshare.net/jrossibarra/population-genetics-of-maize-domestication-adaptation-and-improvement) and [video](https://t.co/89X0DTkGKD) at Dept. of Plant Ag. at U of Guelph.

### Jan. 17, 2014

Happy to announce that [Tim Beissinger](http://scholar.google.com/citations?user=PHAEOXIAAAAJ&hl=en) will be joining the lab as a postdoc in Summer 2014!

### Jan. 14, 2014

Jeff's talks from the Plant And Animal Genome conference are online.  [Bottlenecks](http://www.slideshare.net/jrossibarra/bottlenecks-some-ramblings-and-a-bit-of-data-from-maize) and [deleterious alleles](http://www.slideshare.net/jrossibarra/deleterious-alleles-in-maize-for-pagxxii), oh my!

## 2013

### Dec. 17, 2013

Dianne Velasco passees her QE exams! Congrats D!

Anna O'Brien receives UCMEXUS funding for her dissertation project "Do environmental gradients drive adaptation in mutualisms? A study of teosinte and mycorrhizae".

### Dec. 11, 2013

Lab collaborations on the [Wills et al.](http://f1000.com/prime/718032804) and [Waters et al.](http://f1000.com/prime/718173166) manuscripts have been written up for F1000.

### Dec. 3, 2013

[Pyhäjärvi et al.](http://gbe.oxfordjournals.org/content/5/9/1594) featured on the [cover](http://gbe.oxfordjournals.org/content/5/12.toc) of this months Genome Biology and Evolution.

### Nov. 26, 2013

[Mezmouk et al.](http://m.g3journal.org/content/early/2013/11/18/g3.113.008870.full.pdf) now online at G3

### Nov. 15, 2013

Waters et. al. is now [online at PNAS](http://www.pnas.org/content/early/2013/11/08/1309182110.full.pdf)!

### Nov. 14, 2013

Anna O'Brien passed her qualifying exam and advances to candidacy!

### Nov. 7, 2013

Sofiane's [manuscript](http://arxiv.org/abs/1308.0380) on deleterious alleles and hybrid vigor in maize accepted in [G3](http://www.g3journal.org/)!

Jeff and Vince both added to [list of top genome scientists to follow on twitter](http://nextgenseek.com/2013/11/top-n-genome-scientists-to-follow-on-twitter-2013-edition/).

### October 16, 2013

Video of Jeff's [departmental seminar](https://videocenter.plantsciences.ucdavis.edu/videos/video/26/)
