## Prospective lab members

### Prospective Undergraduates

We are always interested in including undergraduates in our research.  Undergraduate research can be for credit (via a 192 or 199) or as a paid position, depending on current research needs. There are a number of [current research opportunities](research_opps.html) in the lab, but students with prior experience are also encouraged to develop their own independent research projects.  A number of previous undergraduates have successfully [published their work](undergrad_pubs.html).  If you are interested in work in the lab, please take a look at some of the recent [papers from the lab](pubs.html) and contact [Dr. Ross-Ibarra](mailto:rossibarra@ucdavis.edu) with a CV, an unofficial transcript, and a mention of what you're interested in working on, and we can set up an interview!

### Prospective Grad Students

I am currently accepting graduate students through the [Plant Biology](http://biosci3.ucdavis.edu/gradGroups/pb/), [Population Biology](http://www-eve.ucdavis.edu/eve/pbg/), [Ecology](http://ecology.ucdavis.edu), and [Integrated Genetics and Genomics](http://igg.ucdavis.edu) graduate groups. If you're interested in joining my lab, see my [advice for grad school](http://www.slideshare.net/jrossibarra/forgradschool), read a few of our papers, and then contact me and send along a CV.

### Prospective PostDocs

I'm always interested in recruiting talented postdoctoral candidates. In particular, I encourage people to contact me about writing postdoc fellowship proposals for [NSF](http://www.nsf.gov/funding/education.jsp?fund_type=3), [USDA](http://www.csrees.usda.gov/fo/fellowshipsgrantprogramafri.cfm), [CPB](http://cpb.ucdavis.edu/CPB%20Postdoc%20Fellowship.html), [UC MEXUS](http://www.ucmexus.ucr.edu/funding/fellowship_post_doc.html), or any of a number of other fellowship opportunities (see [here](http://mathbionerd.blogspot.com/2014/04/some-postdoctoral-fellowships-in-biology.html) and [here](http://people.ds.cam.ac.uk/dl384/Resources_Postdocs.html) for some nice lists). Please email me with your CV, and I'd be happy to discuss fellowship possibilities.

### Expectations

I view my relationship with students and postdocs as a partnership. My job is to ensure people in the lab get the training and opportunities they need to advance in their chosen careers, whether in academia, industry, teaching, or other options.  In return, I expect lab members to contribute to a productive and friendly environment conducive to learning and research. This includes participation in lab activities such as coffee hour, [REHAB](http://]www.rilab.org/rehab.html), lab meetings, and so on. On average, I expect most students to produce three publications over the course of their PhD, including at least one first-author paper.  I expect somewhat greater productivity from postdocs on average -- approximately 2 papers per year (I believe the actual running average is ~2.5). I strongly encourage collaboration, and a quick glance at our [publications](pubs.html) should show that this generally works well. I also encourage both students and postdocs to take advantage of opportunities to teach, write grants, supervise students, write papers independently or collaborate outside of the lab.

I feel strongly about open science. We write papers on github or [overleaf](overleaf.com), often in public repos.  We publish preprints as soon as a manuscript is ready for submission.  We publish our data as soon as we can, and I am pushing to start doing so as separate data papers. We document our work -- with github, R markdown, readme files, etc. -- so it is intelligible and reusable in the future. I expect members of the lab to practice open science.
