<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5300959-3', 'auto');
  ga('send', 'pageview');

</script>

##R.E.H.A.B.

Science and beer on a Friday afternoon seem to make a good combination.  Nobody presents or defends the papers. We assume everyone has read the paper and jump right in to discussion without introduction.  This allows for a very informal discussion, and with beer involved even the worst papers are much more manageable. Anyone is welcome to come and anyone can [suggest a paper](mailto:rossibarra@ucdavis.edu). There is no email list; articles are posted below along with the date.

We meet Fridays at [de Vere's Irish Pub](http://daviswiki.org/de_Vere%27s_Irish_Pub) at about 4:15 (on rare occasions when the pub is closed we improvise; email or call to find out the location). Sometimes we're done at 5 and sometimes not until 6, depending on the paper and the crowd and interest and amount of beer being consumed.

From time to time we also blog our thoughts on the papers we read. One or more of the people present volunteers to write down some of the discussion of each paper. Our hope is that this is useful to authors in clarifying papers when possible (pre-publication) or to others in considering the potential caveats or points of greatest interest (post-publication). Comments on the blog posts are welcome -- please [email](mailto:rossibarra@ucdavis.edu) them along.

Below are papers for Oct. 2013 and onward. For 2008-2013 papers see [here](old_rehab.html).

We're proud of the growing list of journal clubs modelled on R.E.H.A.B., including  [C.A.M.P.](http://www.public.iastate.edu/~mhufford/HuffordLab/camp/camp.html), [E.H.R.A.B.](http://hagenetics.org/?cat=6), [(Re)views](https://t.co/LYhSgcrgnZ),   [esfoyaza](https://github.com/sawers-rellan-labs/esfoyaza), [Q.U.I.T.](http://jyanglab.com/jc/), [p.r.o.s.t.](https://brandvainlab.wordpress.com/p-r-o-s-t/), [frydomics](https://github.com/arundurvasula/frydomics/blob/master/README.md), and [C.R.O.P.](https://www.cropevolution.org/reading.html)


<!-- [Peer Rebrew](https://kevinabird.wixsite.com/kevinbird/peer-rebrew). -->
<!-- [EvolFri](http://evolfri.blogspot.com/), -->
<!-- [detox](http://beissingerlab.org/Detox/), -->

And no, I won't tell you what R.E.H.A.B. stands for, so don't ask.

## 2019

### January

#### Friday Jan 4
[Zhou et al., preprint](https://www.biorxiv.org/content/early/2018/12/31/508119?rss=1) Structural variants, clonal propagation, and genome evolution in grapevine (Vitis vinifera)

## 2018

### December 

#### Friday December 28
Happy Holidays, no R.E.H.A.B.

#### Friday December 21
Happy Holidays, no R.E.H.A.B.

#### Friday December 14
[Tenaillon et al, preprint](https://www.biorxiv.org/content/early/2018/11/05/461947)
Transcriptomic response to divergent selection for flowering time in maize reveals convergence and key players of the underlying gene regulatory network

#### Friday December 7
[Kelleher et al, preprint](https://www.biorxiv.org/content/early/2018/11/01/458067)
Inferring the ancestry of everyone

### November
#### Friday November 30
[Ruby et al, 2018](http://www.genetics.org/content/210/3/1109)
Estimates of the Heritability of Human Longevity Are Substantially Inflated due to Assortative Mating

#### Friday November 23
No R.E.H.A.B., but in honor of Thanksgiving you can read about the origin of your favorite side dish, [sweet potato](https://www.ncbi.nlm.nih.gov/pubmed/29657119)

#### Friday November 16
[more eLife review!](mailto:rossibarra@ucdavis.edu) email Jeff for link or find on Slack

#### Friday November 9
[Lin et al. 2018](http://www.pnas.org/content/early/2018/10/23/1801437115) Functional and evolutionary genomic inferences in Populus through genome and population sequencing of American and European aspen

#### Friday November 2
Special Seminar -- no R.E.H.A.B.

### October

#### Friday October 26
[Fugère and Hendry, 2018](http://www.pnas.org/content/early/2018/09/12/1806013115)
Human influences on the strength of phenotypic selection

#### Friday October 19
[Tavares et al. 2018](http://www.pnas.org/content/early/2018/10/04/1801832115)
Selection and gene flow shape genomic islands that control floral guides

#### Friday October 12
[Yang et al. 2018](https://nph.onlinelibrary.wiley.com/doi/epdf/10.1111/nph.15296)
Kin recognition in rice (Oryza sativa) lines

#### Friday October 5
[Albers and McVean, preprint](https://www.biorxiv.org/content/early/2018/09/13/416610) Dating genomic variants and shared ancestry in population-scale sequencing data

### September
#### Friday September 28
[eLife review](mailto:rossibarra@ucdavis.edu) email Jeff for link

#### Friday September 21
[Bellon et al., 2018](http://rspb.royalsocietypublishing.org/content/285/1885/20181049) Evolutionary and food supply implications of ongoing maize domestication by Mexican campesinos

#### Friday September 14
[Zuellig et al., 2018](https://onlinelibrary.wiley.com/doi/abs/10.1111/evo.13596) A two‐locus hybrid incompatibility is widespread, polymorphic, and active in natural populations of Mimulus

#### Friday September 7
[Crown et al., 2018](https://www.sciencedirect.com/science/article/pii/S0960982218309035) Local inversion heterozygosity alters recombination throughout the genome

### August
#### Friday August 31
[Fuller et al. 2018](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007526) Ancestral polymorphisms explain the role of chromosomal inversions in speciation

#### Friday August 24
[Simon et al. 2018](https://onlinelibrary.wiley.com/doi/full/10.1002/evl3.66) Coadapted genomes and selection on hybrids: Fisher's geometric model explains a variety of empirical patterns

#### Friday August 17
[Ashander et al. preprint](https://www.biorxiv.org/content/early/2018/06/23/354530) Demographic inference in a spatially-explicit ecological model from genomic data: a proof of concept for the Mojave Desert Tortoise

##### Friday August 10
[Stankowski et al. preprint](https://www.biorxiv.org/content/early/2018/06/21/342352) The tempo of linked selection: Rapid emergence of a heterogeneous genomic landscape during a radiation of monkeyflowers

##### Friday August 3
[Jay et al. 2018](https://www.sciencedirect.com/science/article/pii/S096098221830544X?via%3Dihub) Supergene Evolution Triggered by the Introgression of a Chromosomal Inversion


### July
##### Friday July 27
[Marques et al. 2018](https://www.nature.com/articles/s41559-018-0581-8) Experimental evidence for rapid genomic adaptation to a new niche in an adaptive radiation

##### Friday July 20
[McGlothlin et al. 2018](https://onlinelibrary.wiley.com/doi/full/10.1002/evl3.72) Adaptive radiation along a deeply conserved genetic line of least resistance in Anolis lizards

##### Friday July 13
[Parada and Charlesworth preprint](https://www.biorxiv.org/content/early/2018/06/29/358309) The effects on neutral variability of recurrent selective sweeps and background selection


##### Friday July 6
[Constable and Kokko 2018](https://www.nature.com/articles/s41559-018-0580-9) The rate of facultative sex governs the number of expected mating type


### June

##### Friday June 29
[Smith et al., preprint](https://www.biorxiv.org/content/early/2018/06/03/336503) A domestication history of dynamic adaptation and genomic deterioration in sorghum

##### Friday June 22
[Zou, et al., 2017](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1378-9) Adaptation of Arabidopsis thaliana to the Yangtze River basin

##### Friday June 15
[Fisher, 1918](http://www.indiana.edu/~curtweb/L567/readings/Fisher1918.pdf) The correlation between relatives on the supposition of Mendelian inheritance

##### Friday June 8
[Barghi et al. preprint](https://www.biorxiv.org/content/early/2018/05/28/332122) Polygenic adaptation fuels genetic redundancy in Drosophila

##### Friday June 1
[Flagel et al. preprint](https://www.biorxiv.org/content/early/2018/05/24/330159?rss=1) A synthesis of mapping experiments reveals extensive genomic structural diversity in the Mimulus guttatus species complex

### May
##### Friday May 25
[Corbett-Detig et al. manuscript (email for pdf)](mailto:rossibarra@ucdavis.edu) Bulk Pollen Sequencing Reveals Rapid Evolution of Segregation Distortion In The Male Germline of Arabidopsis Hybrids 

##### Friday May 18
[Raynes et al. 2018](http://www.pnas.org/content/pnas/115/13/3422.full.pdf) Sign of selection on mutation rate modifiers depends on population size

##### Friday May 11
[Kelly 2018](https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msy043/4960043) The amount of nitrogen used for photosynthesis modulates molecular evolution in plants 


##### Friday May 4
[Kern and Hahn 2018](https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msy092/4990884) The neutral theory in light of natural selection

### April
##### Friday Apr. 27
**Note: REHAB at 3pm at 3rd and U**  
[Schumer et al. 2018](http://science.sciencemag.org/content/early/2018/04/18/science.aar3684) Natural selection interacts with recombination to shape the evolution of hybrid genomes

##### Friday Apr. 20  
[Zeng et al. 2018](https://www.nature.com/articles/s41588-018-0101-4) Signatures of negative selection in the genetic architecture of human

##### Friday Apr. 13  
[Gage et al. preprint](https://www.biorxiv.org/content/early/2018/03/18/284109) Selection signatures underlying dramatic male inflorescence transformation during modern hybrid maize breeding [[commentary](http://disq.us/p/1rsk6oq)]

##### Friday Apr. 6  
[Yeaman et al. preprint](https://www.biorxiv.org/content/early/2018/03/09/279661) Quantifying how constraints limit the diversity of viable routes to adaptation

### March

##### Friday Mar. 30   
MGC -- no R.E.H.A.B.

##### Friday Mar. 23  
MGC -- no R.E.H.A.B.

##### Friday Mar. 16
[Booker and Keightley preprint](https://www.biorxiv.org/content/early/2018/03/02/275610) Understanding the factors that shape patterns of nucleotide diversity in the house mouse genome

##### Friday Mar. 9
[Filiault et al. preprint](https://www.biorxiv.org/content/early/2018/02/12/264101) The Aquilegia genome: adaptive radiation and an extraordinarily polymorphic chromosome with a unique history

##### Friday Mar. 2
[di Iulio et al. 2018](https://www.nature.com/articles/s41588-018-0062-7) The human noncoding genome defined by genetic diversity

### February
##### Friday Feb. 23
[Willi et al. 2018](https://www.ncbi.nlm.nih.gov/pubmed/29346601) Accumulation of mutational load at the edges of a species range.

##### Friday Feb. 16
[Huang et al. 2018](http://www.pnas.org/content/115/2/E334) ZmCCT9 enhances maize adaptation to higher latitudes

##### Friday Feb. 9
[Kong et al. 2018](http://science.sciencemag.org/content/359/6374/424) The nature of nurture: Effects of parental genotypes

##### Friday Feb. 2
[Ørsted et al. 2017](http://onlinelibrary.wiley.com/doi/10.1111/evo.13391/full) Environmental variation partitioned into separate heritable components

### January
##### Friday Jan. 26
[Hayward et al. 2017](http://www.genetics.org/content/early/2017/11/10/genetics.117.300498) Evidence for Selection-by-Environment but Not Genotype-by-Environment Interactions for Fitness-Related Traits in a Wild Mammal Population

##### Friday Jan. 19
[Borges et al. 2018](https://www.nature.com/articles/s41588-017-0032-5) Transposon-derived small RNAs triggered by miR845 mediate genome dosage response in *Arabidopsis*

##### Friday Jan. 12
No R.E.H.A.B. (lab at Plant and Animal Genome conference)

##### Friday Jan. 5
[Patwa & Wahl 2008](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2607448/pdf/rsif20080248.pdf) The fixation probability of beneficial mutations

## 2017
### December

##### Dec. 22, 29 No R.E.H.A.B. -- Happy Holidays!

##### Friday Dec. 15
[Murray et al. 2017](http://science.sciencemag.org/content/358/6365/951) Natural selection shaped the rise and fall of passenger pigeon genomic diversity

##### Friday Dec. 8
[Comeron 2017](http://rstb.royalsocietypublishing.org/content/372/1736/20160471) Background selection as null hypothesis in population genomics: insights and challenges from Drosophila studies

##### Friday Dec. 1
[Gienapp et al. 2017](https://sci-hub.cc/http://www.sciencedirect.com/science/article/pii/S0169534717302343) Genomic Quantitative Genetics to Study Evolution in the Wild

...and a special thanks to John Burke for making me owe Matt Hufford a beer.

### November
##### Friday Nov 24
No R.E.H.A.B., but in honor of Thanksgiving you can bone up on your statistics by learning about [Turkey's test](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&as_ylo=2017&q=%22turkey%27s+test%22&btnG=).

##### Friday Nov 17
[ Zan and Carlborg preprint](https://www.biorxiv.org/content/early/2017/10/20/206706?rss=1&utm_source=dlvr.it&utm_medium=twitter) Explorations of the polygenic genetic architecture of flowering time in the worldwide Arabidopsis thaliana population

##### Friday Nov 10
[Bosse et al. 2017](http://science.sciencemag.org/content/358/6361/365) Recent natural selection causes adaptive evolution of an avian polygenic trait

##### Friday Nov 3
[Schrider & Kern preprint](https://www.biorxiv.org/content/early/2017/10/20/206482) Machine Learning for Population Genetics: A New Paradigm

### October
##### Friday Oct 27
[Osada et al. 2017](http://www.genetics.org/content/206/4/2139) Cis- and Trans-regulatory Effects on Gene Expression in a Natural Population of Drosophila melanogaster

##### Friday Oct 20
[Lotterhos et al. preprint](https://www.biorxiv.org/content/early/2017/10/13/202481) Modular environmental pleiotropy of genes involved in local adaptation to climate despite physical linkage

##### Friday Oct 13
[Forsythe et al preprint](https://www.biorxiv.org/content/early/2017/10/02/197087) Epistatic interactions drive biased gene retention in the face of massive nuclear introgression

##### Friday Oct 6
[Salojärvi et al. 2017](http://dx.doi.org/10.1038/ng.3862) Genome sequencing and population genomic analyses provide insights into the adaptive landscape of silver birch.

### September
##### Friday Sept 29
[Huber et al preprint](http://www.biorxiv.org/content/early/2017/08/31/182865) Gene expression drives the evolution of dominance

##### Friday Sept 22
[Jain and Stephan 2017](https://academic.oup.com/mbe/article-abstract/doi/10.1093/molbev/msx240/4110473/Modes-of-rapid-polygenic-adaptation?redirectedFrom=fulltext) Modes of rapid polygenic adaptation

##### Friday Sept 15
[Gage et al. 2017]() The effect of artificial selection on phenotypic plasticity in maize ([email](mailto:rossibarra@ucdavis.edu) or see lab Slack for paper)

##### Friday Sept 8
[Oka et al. 2017](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1273-4) Genome-wide mapping of transcriptional enhancer candidates using DNA and chromatin features in maize

##### Friday Sept 1
R.E.H.A.B. joint paper review. ([email](mailto:rossibarra@ucdavis.edu) or see lab Slack for paper)

### August
##### Friday Aug 25
[Zhang and Gao 2017](http://www.g3journal.org/content/7/6/1875) Rapid and Recent Evolution of LTR Retrotransposons Drives Rice Genome Evolution During the Speciation of AA-Genome Oryza Species

##### Friday Aug 18
[González-Martínez4 et al. 2017](http://www.cell.com/current-biology/fulltext/S0960-9822(17)30865-5) Range Expansion Compromises Adaptive Evolution in an Outcrossing Plant

##### Friday Aug 11
[Hübner et al. 2017]() The Cultivated Sunflower Pan Genome Provides Insights on the Contribution of Introgressions to Breeding of Modern Varieties 

##### Friday Aug 4
No R.E.H.A.B.

### July
##### Friday July 28
[Zan et al. 2017](https://academic.oup.com/mbe/article-lookup/doi/10.1093/molbev/msx194) Artificial selection response due to polygenic adaptation from a multi-locus, multi-allelic genetic architecture

##### Friday July 21 
[Sohail et al 2017](http://science.sciencemag.org/content/356/6337/539) Negative selection in humans and fruit flies involves synergistic epistasis

##### Friday July 14
[Chen et al. 2017](https://academic.oup.com/mbe/article-abstract/34/6/1417/3049540/Genetic-Diversity-and-the-Efficacy-of-Purifying?redirectedFrom=PDF) Genetic Diversity and the Efficacy of Purifying Selection across Plant and Animal Species

##### Friday July 7
[Hurst and Randerson 2000](http://www.sciencedirect.com.sci-hub.cc/science/article/pii/S0022519300920952)
Dosage, Deletions and Dominance: Simple Models of the Evolution of Gene Expression

### June
##### Friday June 30
[Vijay et al. 2017](http://onlinelibrary.wiley.com/doi/10.1111/mec.14195/full) Genome-wide patterns of variation in genetic diversity are shared among populations, species and higher order taxa

##### Friday June 23
[Gould et al. preprint](http://biorxiv.org/content/early/2017/06/03/145805) The Gene Regulatory Landscape of Local Adaptation

##### Friday June 16
[Zeng et al. preprint](http://biorxiv.org/content/early/2017/06/03/145755) Widespread signatures of negative selection in the genetic architecture of human complex traits

##### Friday June 9
[Simons et al. 2017](https://arxiv.org/abs/1704.06707) A model for the genetic architecture of quantitative traits under stabilizing selection

##### Friday June 2
[Walter et al. preprint](http://biorxiv.org/content/early/2017/01/02/097642) 
Evolution of genetic variance during adaptive radiation

### May
##### Friday May 26
[Lee et al. 2017](https://www.nature.com/articles/s41559-017-0119) Young inversion with multiple linked QTLs under selection in a hybrid zone

##### Friday May 19
[Corbett-Detig et al. 2015](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002112) Natural Selection Constrains Neutral Diversity across A Wide Range of Species

*AND*

[Coop 2016 preprint](http://biorxiv.org/content/early/2016/03/07/042598) Does linked selection explain the narrow range of genetic diversity across species?

##### Friday May 12
[Durvasula et al. 2017](http://www.pnas.org/content/early/2017/05/03/1616736114.abstract) African genomes illuminate the early history and transition to selfing in Arabidopsis thaliana

##### Friday May 5
[Gilbert et al. 2017](http://www.journals.uchicago.edu/doi/abs/10.1086/690673) Local Adaptation Interacts with Expansion Load during Range Expansion: Maladaptation Reduces Expansion Load

### April
##### Friday April 28
[Gilbert and Whitlock 2017](http://onlinelibrary.wiley.com/doi/10.1111/jeb.13029/full) The genetics of adaptation to discrete heterogeneous environments: frequent mutation or large‐effect alleles can allow range expansion

##### Friday April 21
[Huang, Gulko & Siepel 2017](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3810.html?WT.feed_name=subjects_genetics) Fast, scalable prediction of deleterious noncoding variants from functional and population genomic data

##### Friday April 14
[Wang et al. 2017](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3807.html#f1) Asymmetric subgenome selection and cis-regulatory divergence during cotton domestication

##### Friday April 7
[Charlesworth 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3730922/) Stabilizing Selection, Purifying Selection, and Mutational Bias in Finite Populations

### March
##### Friday March 31
[Franssen et al. 2017](http://www.nature.com/hdy/journal/v118/n1/full/hdy201698a.html) Uncovering the genetic signature of quantitative trait evolution with replicated time series data

##### Friday March 24
[Hermisson & Pennings preprint](http://biorxiv.org/content/early/2017/03/07/114587) Soft sweeps and beyond: Understanding the patterns and probabilities of selection footprints under rapid adaptation

##### Friday March 17
[Brandenburg et al 2017](https://rilab.slack.com/archives/papers/p1489556863288990) Independent introductions and admixtures have contributed to adaptation of European maize and its American counterparts 

##### Friday March 10
[Maize meeting](http://www.maizegdb.org/maize_meeting/2017/) -- no R.E.H.A.B.

##### Friday March 3
[Messer and Petrov 2013](https://www.ncbi.nlm.nih.gov/pubmed/24075201) Population genomics of rapid adaptation by soft selective sweeps.

### February 2017
##### Friday Feb. 24
[Robillard et al 2016](http://www.pnas.org/content/113/51/14763.abstract) Experimental evolution reveals hyperparasitic interactions among transposable elements

##### Friday Feb. 17
[Watson et al. 2016](http://www.pnas.org/content/113/43/12226.abstract) Germline replications and somatic mutation accumulation are independent of vegetative life span in *Arabidopsis*

##### Friday Feb. 10
Two papers on enhancers and diversity. If short of time, read [Ludwig et al.](http://www.nature.com/nature/journal/v403/n6769/full/403564a0.html) first.

**1)** [Ludwig et al. 2000](http://www.nature.com/nature/journal/v403/n6769/full/403564a0.html) Evidence for stabilizing selection in a eukaryotic enhancer element  
**2)** [Alexandre et al preprint](http://biorxiv.org/content/early/2017/01/30/104323) Regulatory DNA in A. thaliana can tolerate high levels of sequence divergence

##### Friday Feb. 3
[Wagner et al. 2017](http://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12653/abstract) Spatial detection of outlier loci with Moran eigenvector maps (MEM)

### January 2017

##### Friday Jan 27
[Weir and Goudet preprint](http://www.biorxiv.org/content/early/2016/11/17/088260) A unified characterization of population structure and relatedness.

##### Friday Jan 20
[Puzey et al 2016](http://onlinelibrary.wiley.com/doi/10.1111/mec.13922/full) Population structure and local selection yield high genomic variation in Mimulus guttatus

##### Friday Jan 13
PAG - no R.E.H.A.B.

##### Friday Jan 6
[Vidalis et al. 2016](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1127-5) Methylome evolution in plants

## 2016

### December 2016
##### Friday Dec. 30
No R.E.H.A.B. Happy new year!

##### Friday Dec. 23
No R.E.H.A.B. Happy [Festivus](https://en.wikipedia.org/wiki/Festivus)!

##### Friday Dec. 16
[Barton 2016](http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy2016109a.html) How does epistasis influence the response to selection?

##### Friday Dec. 9
[Imprialou et al. preprint](http://biorxiv.org/content/early/2016/11/12/087387) Genomic Rearrangements Considered as Quantitative Traits

##### Friday Dec 2
[Klasen et al 2016](http://www.nature.com/articles/ncomms13299) A multi-marker association method for genome-wide association studies without the need for population structure correction

### November 2016
##### Friday Nov 25
No R.E.H.A.B. -- Turkey Day!

##### Friday Nov 18
[Moyerbrailean et al. 2016](http://genome.cshlp.org/content/early/2016/10/18/gr.209759.116) High-throughput allele-specific expression across 250 environmental conditions

##### Friday Nov 11
No R.E.H.A.B. - Veteran's Day

##### Friday Nov 4
[Gould et al. 2016](http://onlinelibrary.wiley.com/doi/10.1111/mec.13881/abstract) Pooled Ecotype Sequencing Reveals Candidate Genetic Mechanisms for Adaptive Differentiation and Reproductive Isolation

### October 2016
##### Friday Oct 28
[Phung et al preprint](http://biorxiv.org/content/early/2015/11/14/031740) Natural selection reduces linked neutral divergence between distantly related species

##### Friday Oct 21
[Johnsson](http://www.nature.com/articles/ncomms12950) Feralisation targets different genomic loci to domestication in the chicken

##### Friday Oct 14
[Fraïsse et al. 2014](http://www.genetics.org/content/197/3/939.short) Gene-Flow in a Mosaic Hybrid Zone: Is Local Introgression Adaptive?

##### Friday Oct 7
[Willing et al. 2016](http://www.nature.com/articles/nplants201423) Genome expansion of Arabis alpina linked with retrotransposition and reduced symmetric DNA methylation

### September 2016
##### Friday Sept 30
[Schrider et al. 2016](http://www.genetics.org/content/early/2016/09/06/genetics.116.190223) Effects of Linked Selective Sweeps on Demographic Inference and Model Selection

##### Friday Sept 23
[Hughes, Langdale, Kelly 2016](http://genome.cshlp.org/content/24/8/1348.full) The impact of widespread regulatory neofunctionalization on homeolog gene evolution following whole-genome duplication in maize

##### Friday Sept 16
[Groth and Blumenstiel 2016](http://jhered.oxfordjournals.org/content/early/2016/08/24/jhered.esw050.abstract) Horizontal transfer can drive a greater transposable element load in large populations

##### Friday Sept 9
[Venkataram et al 2016](http://www.cell.com/cell/fulltext/S0092-8674(16)31010-8#) Development of a Comprehensive Genotype-to-Fitness Map of Adaptation-Driving Mutations in Yeast

##### Friday Sept 2
[Uricchio et al. 2016](http://genome.cshlp.org/content/early/2016/05/18/gr.202440.115.abstract?papetoc) Selection and explosive growth alter genetic architecture and hamper the detection of causal rare variants

### August 2016
##### Friday Aug 26
[Zhang et al. 2016](http://mbe.oxfordjournals.org/content/early/2016/08/10/molbev.msw169) Recombination rate variation, hitchhiking, and demographic history shape deleterious load in poplar

##### Friday Aug 19
[Fransz et al. 2016](http://onlinelibrary.wiley.com/doi/10.1111/tpj.13262/full) Molecular, genetic and evolutionary analysis of a paracentric inversion in Arabidopsis thaliana

##### Friday August 12
[Fu et al 2016](http://www.nature.com/nature/journal/v534/n7606/full/nature17993.html) The genetic history of Ice Age Europe

##### Friday Aug 5
[Sanseverino et al. 2015](http://www.ncbi.nlm.nih.gov/pubmed/26174143?dopt=Abstract&utm_source=dlvr.it&utm_medium=twitter) Transposon Insertions, Structural Variations, and SNPs Contribute to the Evolution of the Melon Genome.

### July 2016
##### Friday July 29
[Russel et al 2016](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3612.html) Exome sequencing of geographically diverse barley landraces and wild relatives gives insights into environmental adaptation

**AND**

[Lasky et al. 2015](http://advances.sciencemag.org/content/1/6/e1400218) Genome-environment associations in sorghum landraces predict adaptive traits


##### Friday July 22
[Sharp & Agrawal 2016](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002419) Low Genetic Quality Alters Key Dimensions of the Mutational Spectrum

[blog post](blogs/22072016.html)

##### Friday July 15
[Arnold et al. 2016](http://www.pnas.org/content/early/2016/06/28/1600405113.abstract) Borrowed alleles and convergence in serpentine adaptation


##### Friday July 8
[Bailey et a 2015](http://m.mbe.oxfordjournals.org/content/early/2015/03/26/molbev.msv033.full) The Effect of Selection Environment on the Probability of Parallel Evolution

##### Friday July 1
[Zhena and Andolfatto 2012](http://link.springer.com/protocol/10.1007%2F978-1-61779-585-5_6) Methods to Detect Selection on Noncoding DNA

### June 2016

##### Friday June 24 2016
[Quadrana et al](https://elifesciences.org/content/5/e15716) The Arabidopsis thaliana mobilome and its impact at the species level

##### Friday June 17 2016
[1001 Genomes Consortium](http://www.cell.com/cell/abstract/S0092-8674(16)30667-5) 1,135 Genomes Reveal the Global Pattern of Polymorphism in Arabidopsis thaliana

##### Friday June 10 2016
[Cardoso-Moreira et al. 2016](http://m.genome.cshlp.org/content/26/6/787) Evidence for the fixation of gene duplications by positive selection in Drosophila

##### Friday June 3 2016
[Wales et al. 2016](https://rilab.slack.com/files/jri/F1CQU52JX/th162_curbioreport_300516-2.pdf) Genome sequence of a 5300-year-old maize cob recovered from the Tehuacan Valley provides insights into the early stages of maize domestication

### May 2016
##### Friday May 27 2016
[Paccard et al 2016](http://www.journals.uchicago.edu/doi/pdfplus/10.1086/685643) Quantitative Genetic Architecture at Latitudinal Range Boundaries: Reduced Variation but Higher Trait Independence

##### Friday May 20 2016
[Keightley et al 2016](http://www.genetics.org/content/early/2016/04/18/genetics.116.188102) Inferring the Frequency Spectrum of Derived Variants to Quantify Adaptive Molecular Evolution in Protein-Coding Genes of Drosophila melanogaster

##### Friday May 13 2016
[Exposito-Alonso et al preprint](http://biorxiv.org/content/early/2016/04/25/050203) The rate and effect of de novo mutations in natural populations of Arabidopsis thaliana

##### Friday May 6 2016
[Kelley et al 2016](http://onlinelibrary.wiley.com/doi/10.1111/mec.13573/abstract?wol1URL=/doi/10.1111/mec.13573/abstract&regionCode=US-CA&identityKey=77f2fe64-6ec1-4c14-a95a-63aa4a9960d1) The multivariate association between genomewide DNA methylation and climate across the range of Arabidopsis thaliana

##### Friday April 29 2016
[Roles et al. 2016](http://onlinelibrary.wiley.com/doi/10.1111/evo.12913/abstract) Field measurements of genotype by environment interaction for fitness caused by spontaneous mutations in Arabidopsis thaliana

### April 2016

##### Friday April 22 2016
[Sanjak et al. preprint](http://biorxiv.org/content/early/2016/04/15/048819) The Genetic Architecture of a Complex Trait is more Sensitive to Genetic Model than Population Growth

##### Friday April 15 2016
Novikova et al. manuscript (see \#papers channel on slack for pdf)

##### Friday April 8 2016
[He and Knowles 2016](http://onlinelibrary.wiley.com/doi/10.1111/mec.13619/full) Identifying targets of selection in mosaic genomes with machine learning: applications in Anopheles gambiae for detecting sites within locally adapted chromosomal inversions

##### Friday April 1 2016
[Lolle et al. 2005](http://www.genetics.org/content/early/2016/03/21/genetics.115.184630) Genome-wide non-mendelian inheritance of extra-genomic information in Arabidopsis.

### March 2016
##### Friday Mar 25
[Marschall et al. preprint](http://biorxiv.org/content/early/2016/03/12/043430) Computational Pan-Genomics: Status, Promises and Challenges

##### Friday Mar 18
No R.E.H.A.B. (Maize Meeting!)

##### Friday Mar 11
[Lamichhaney et al. 2012](http://www.pnas.org/content/109/47/19345.short)
 Population-scale sequencing reveals genetic differentiation due to local adaptation in Atlantic herring

##### Friday Mar 4
[Keller and Fitzpatrick 2014](http://onlinelibrary.wiley.com/doi/10.1111/ele.12376/abstract) Ecological genomics meets community-level modelling of biodiversity: mapping the genomic landscape of current and future environmental adaptation

### February 2016

##### Fri. Feb 26
[Rausher and Delph 2015](http://onlinelibrary.wiley.com/doi/10.1111/evo.12687/abstract) When does understanding phenotypic evolution require identification of the underlying genes?

##### Fri. Feb 19 2016
[Gao et al 2015](http://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0867-y) Landscape and evolutionary dynamics of terminal repeat retrotransposons in miniature in plant genomes

##### Fri. Feb 12 2016
[Mäki-Tanila and Hill](http://genetics.org/content/early/2014/06/26/genetics.114.165282.full-text.pdf+html) Influence of Gene Interaction on Complex Trait Variation with Multi-Locus Models

##### Fri. Feb 5 2016
[Sheehan and Song preprint](http://biorxiv.org/content/biorxiv/early/2015/10/02/028175.full.pdf) Deep learning for population genetic inference

### January 2016
##### Fri. Jan 29 2016
[Lamichhaney  et al. 2016](http://www.ncbi.nlm.nih.gov/pubmed/26569123) Structural genomic changes underlie alternative reproductive strategies in the ruff (Philomachus pugnax).

##### Fri. Jan 22 2016
[Stephan 2016](http://onlinelibrary.wiley.com/doi/10.1111/mec.13288/epdf) Signatures of positive selection: from selective sweeps atindividual loci to subtle allele frequency changes inpolygenic adaptation

##### Fri. Jan 15 2016
[Bainard et al. 2012](http://www.ncbi.nlm.nih.gov/pubmed/23078229) A multivariate analysis of variation in genome size and endoreduplication in angiosperms reveals strong phylogenetic signal and association with phenotypic traits

##### Fri. Jan 8 2016
[Marsden et al. 2015](http://www.pnas.org/content/early/2015/12/17/1512501113.long) Bottlenecks and selective sweeps during domestication have increased deleterious genetic variation in dogs

## 2015
### December 2015
##### Fri. Dec. 18 2015
[Steige et al. preprint](http://biorxiv.org/content/early/2015/12/10/034025) The impact of natural selection on the distribution of cis-regulatory variation across the genome of an outcrossing plant

##### Fri. Dec. 11 2015
[Mascagni et al. 2015](http://gbe.oxfordjournals.org/content/early/2015/11/24/gbe.evv230.short?rss=1&utm_source=dlvr.it&utm_medium=twitter) Repetitive DNA and plant domestication: variation in copy number and proximity to genes of LTR-retrotransposons among wild and cultivated sunflower (Helianthus annuus) genotypes.

##### Fri. Dec. 4 2015
[Remington 2015](http://www.ncbi.nlm.nih.gov/pubmed/26374707) Alleles versus mutations: Understanding the evolution of genetic architecture requires a molecular perspective on allelic origins.

### November 2015

##### Fri. Nov. 27 2015
No R.E.H.A.B. for the holidays. But you can get your fill of [turkey popgen](http://www.biomedcentral.com/1471-2156/15/117/) nonetheless.

##### Fri. Nov. 20 2015
[Beissinger et al. 2015](https://github.com/RILAB/beissinger_ms/raw/master/manuscript_submit.pdf) Recent demography drives changes in linked selection across the maize genome

##### Fri. Nov. 13 2015

[van Heerwaarden et al. 2015](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005594) Genome-Wide Association Analysis of Adaptation Using Environmentally Predicted Traits

##### Fri. Nov. 6 2015

[Scheiner et al. 2015](http://www.jstor.org/stable/10.1086/680552) The Genetics of Phenotypic Plasticity. XIV. Coevolution

### October 2015

##### Fri. Oct. 30 2015

[Chevin and Hospital 2008](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2581964/) (AGAIN!) Selective Sweep at a Quantitative Trait Locus in the Presence of Background Genetic Variation

##### Fri. Oct. 23 2015

[Chevin and Hospital 2008](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2581964/) Selective Sweep at a Quantitative Trait Locus in the Presence of Background Genetic Variation

##### Fri. Oct. 16 2015

[Raghavan et al. 2015](http://www.sciencemag.org/content/349/6250/aab3884.full.pdf) Genomic evidence for the Pleistocene and recent population history of Native Americans

**AND**

[Skoglund et al. 2015](http://www.nature.com/articles/nature14895.epdf?referrer_access_token=tF-nTz-prCDEH27ShnkdPdRgN0jAjWel9jnR3ZoTv0N6yB-nEyCdRoL51ykMO5E91orKw8mXMzuxoORJJBQhEqcxnwkIiI9eF80kfbg_ZrqmuZw6FTNFC8G_t31NWwGTUNhn_xmpabdr3EDodtD6tQ4AqlmsBeTdeFjIrgbc4bKOCYfPhWfbbNt9PySbQ_si&tracking_referrer=www.bbc.com) Genetic evidence for two founding populations of the Americas

##### Fri. Oct. 9 2015

[Heath and Nuismer 2014](http://www.ncbi.nlm.nih.gov/pubmed/24782890) Connecting functional and statistical definitions of genotype by genotype interactions in coevolutionary studies

##### Fri. Oct. 2 2015

[Wang et al. 2015](http://www.pnas.org/content/112/35/E4959.long) Hybrid mimics and hybrid vigor in Arabidopsis

[blog post](http://www.rilab.org/blogs/02102015.html)

### September 2015

##### Fri. Sept. 25 2015

[Lande and Arnold 1983](http://people.oregonstate.edu/~arnoldst/pdf_files/Lande%20&%20Arnold%201983.pdf) The measurement of selection on correlated characters

##### Fri. Sept. 18 2015

[Thornton et al. 2013](http://www.plosgenetics.org/article/info:doi/10.1371/journal.pgen.1003258) Properties and Modeling of GWAS when Complex Disease Risk Is Due to Non-Complementing, Deleterious Mutations in Genes of Large Effect

##### Fri. Sept. 11 2015

[Renaut and Reiseberg 2015](http://mbe.oxfordjournals.org/content/32/9/2273) The Accumulation of Deleterious Mutations as a Consequence of Domestication and Improvement in Sunflowers and Other Compositae Crops

##### Fri. Sept. 4 2015

[Kuester et al. preprint](http://biorxiv.org/content/early/2015/08/20/024950) A resurrection experiment finds evidence of both reduced genetic diversity and adaptive evolution in the agricultural weed Ipomoea purpurea

### August 2015

##### Fri. Aug. 28 2015

[Weis et al. 2015](http://onlinelibrary.wiley.com/doi/10.1111/evo.12677/abstract) Hard and soft selection on phenology through seasonal shifts in the general and social environments: A study on plant emergence time

##### Fri. Aug. 21 2015

[Snir et al. 2015](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0131422) The Origin of Cultivation and Proto-Weeds, Long Before Neolithic Farming

##### Fri. Aug. 14 2015

[Dubin et al. 2015](http://elifesciences.org/content/4/e05255) DNA methylation in Arabidopsis has a genetic basis and shows evidence of local adaptation

##### Fri. Aug. 7 2015

[Castellano et al. preprint](http://biorxiv.org/content/early/2015/06/27/021600) Adaptive evolution is substantially impeded by Hill-Robertson interference in Drosophila

### July 2015

##### Fri. July 31 2015

**Myriad Mutation Models: Three papers on heterozygote impacts on mutation**

[Yang et al. 2015](http://www.nature.com/nature/journal/v523/n7561/full/nature14649.html) Parent–progeny sequencing indicates higher mutation rates in heterozygotes

[Hollister et al. 2010](http://mbe.oxfordjournals.org/content/27/2/409.abstract) Indel-Associated Mutation Rate Varies with Mating System in Flowering Plants

[Tian et al. 2008](http://www.nature.com/nature/journal/v455/n7209/abs/nature07175.html) Single-nucleotide mutation rate increases close to insertions/deletions in eukaryotes

##### Fri. July 24 2015

[Mazet et al. 2015](http://arxiv.org/abs/1412.1243) Demographic inference using genetic data from a single individual: separating population size variation from population structure

##### Fri. July 17 2015

[Oakley et al 2015](http://www.nature.com/hdy/journal/v115/n1/full/hdy201518a.html) Heterosis and outbreeding depression in crosses between natural populations of Arabidopsis thaliana

##### Fri. July 10 2015

[Monnahan et al. 2015](http://onlinelibrary.wiley.com/doi/10.1111/evo.12698/abstract) A genomic selection component analysis characterizes migration-selection balance

##### Fri. July 3 2015

[Fierst et al. 2015](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005323) Reproductive Mode and the Evolution of Genome Size and Structure in Caenorhabditis Nematodes

### June 2015

##### Fri. June 26 2015

[Asaf et al. 2015](http://m.pnas.org/content/112/20/E2658.abstract) Obstruction of adaptation in diploids by recessive, strongly deleterious alleles

##### Fri. June 19 2015

[Mafessoni and Lachman preprint](http://biorxiv.org/content/biorxiv/early/2015/03/23/016881.full.pdf)
Selective strolls: fixation and extinction in diploids are slower for weakly selected mutations than for neutral ones

##### Fri. June 12 2015

[Pease and Hahn 2015](http://sysbio.oxfordjournals.org/content/early/2015/04/17/sysbio.syv023.long) Detection and Polarization of Introgression in a Five-taxon Phylogeny

##### Fri. June 5 2015

[Wilkes 1977](http://www.jstor.org/stable/4253844?seq=1#page_scan_tab_contents) Hybridization of Maize and Teosinte, in Mexico and Guatemala and the Improvement of Maize

### May 2015

##### Fri. May 29, 2015

[Van der Graf 2015](http://www.pnas.org/content/112/21/6676.abstract) Rate, spectrum, and evolutionary dynamics of spontaneous epimutations.


##### Fri. May 22, 2015

[Monnahan and Kelly 2015](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005201) Epistasis Is a Major Determinant of the Additive Genetic Variance in Mimulus guttatus

##### Fri. May 15, 2015

[Mathieson and McVean 2013](http://www.ncbi.nlm.nih.gov/pubmed/23307902) Estimating selection coefficients in spatially structured populations from time series data of allele frequencies

##### Fri. May 8, 2015

[Sheng et al. preprint](http://biorxiv.org/content/early/2015/04/29/018721) Standing genetic variation as a major contributor to adaptation in the Virginia chicken lines selection experiment

##### Fri. May 1, 2015

[Fishman and Kelly 2015](http://onlinelibrary.wiley.com/doi/10.1111/evo.12661/abstract;jsessionid=0A4565C367B1ED7DA47A6F1989FF4009.f02t02) Centromere–associated meiotic drive and female fitness variation in Mimulus

[blog post](blogs/01052015.html)

### April 2015

##### Fri. April 24, 2015

[Agren et al. 2014](http://onlinelibrary.wiley.com/doi/10.1111/evo.12627/abstract;jsessionid=1E212DDEDBAC6D87C26FC8A5FA7F134F.f03t02) No evidence that sex and transposable elements drive genome size variation in evening primroses

##### Fri. April 17, 2015

[Douglas et al. 2015](http://www.pnas.org/content/112/9/2806.abstract) Hybrid origins and the earliest stages of diploidization in the highly successful recent polyploid Capsella bursa-pastoris

##### Fri. April 10, 2015

No R.E.H.A.B. Come to the [UCDavis Plant Breeding Symposium](http://plantbreeding2015.ucdavis.edu/) instead.

##### Fri. April 3, 2015

Romero et al. SeeDs manuscript (email Jeff for the URL).

### March 2015

##### Fri. March 27, 2015

Cesar Chavez Day; university closed. No R.E.H.A.B.

##### Fri. March 20, 2015

[Jeffares et al 2015](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3215.html) The genomic and phenotypic diversity of Schizosaccharomyces pombe

##### Fri. March 13, 2015

NO R.E.H.A.B. -- [MGC](http://www.maizegdb.org/maize_meeting/2015/) baby!

##### Fri. March 6, 2015

[Bergland et al 2014](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1004775) Genomic Evidence of Rapid and Stable Adaptive Oscillations over Seasonal Time Scales in Drosophila

### February 2015

##### Fri. Feb. 27, 2015

[Brown and Levin 2011](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3437465/) Social dilemmas among supergenes: intragenomic sexual conflict and a selfing solution in Oenothera

##### Fri. Feb. 20, 2015

[Huang et al 2014](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1004527) Genome-Wide Patterns of Genetic Variation within and among Alternative Selective Regimes

##### Fri. Feb. 13, 2015

Li et al. Methylation manuscript. (printed version available from JRI).

##### Fri. Feb. 6, 2015

Rodgers-Melnick  et al. Recombination manuscript. (printed version available from JRI).

### January 2015

##### Fri. Jan 30, 2015

[Brandvain et al. 2014](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1004410) Speciation and Introgression between Mimulus nasutus and Mimulus guttatus

##### Fri. Jan 23, 2015

[Charlesworth 2015](http://www.pnas.org/content/early/2015/01/07/1423275112.abstract) Causes of natural variation in fitness: Evidence from studies of Drosophila populations

##### Fri. Jan 16, 2015

[Antonovics 1976](http://www.jstor.org/stable/2395303) The nature of limits to natural selection.

##### Fri. Jan 9, 2015
[Wiser et al. 2013](http://www.sciencemag.org/content/342/6164/1364) Long-Term Dynamics of Adaptation in Asexual Populations

##### Fri. Jan 2, 2015

No R.E.H.A.B., but celebrate the new year in plant genomics by [reading up on cotton](http://www.nespal.org/peng_lab/papers/S1687537008742304.pdf), including the C-genome species that are 2015 megabases in size.

## 2014

### December 2014

##### Fri. Dec. 26, 2014

No R.E.H.A.B., but feel free to get your plant genomics fix by reading up on the [Christmas Tree genome](http://www.nature.com/nature/journal/v497/n7451/full/nature12211.html)

##### Fri. Dec. 19, 2014

R.E.H.A.B. unexpectedly cancelled due to lab partying (seriously).

##### Fri. Dec. 12, 2014

[Poh et al. preprint](http://biorxiv.org/content/biorxiv/early/2014/09/29/009456.full.pdf) On the prospect of identifying adaptive loci in recently bottlenecked populations

##### Fri. Dec. 5, 2014

[Fu et al. 2014](http://www.sciencedirect.com/science/article/pii/S0002929714003899) Characteristics of Neutral and Deleterious Protein-Coding Variation among Individuals and Populations

### November 2014

##### Fri. Nov. 28, 2014

No REHAB. But that doesn't meant you can't get a second helping of [turkey genomics](http://ps.oxfordjournals.org/content/93/2/479.short) should you so desire.

##### Fri. Nov. 21, 2014

[Takuno et al. in prep](https://github.com/rossibarra/hilo_paper/blob/master/HighLow.pdf?raw=true) Independent molecular basis of convergent highland adaptation in maize

##### Fri. Nov. 14, 2014

[Gravel preprint](http://biorxiv.org/content/early/2014/10/30/010934) When is selection effective?

##### Fri. Nov. 7, 2014

[Hough et al. 2014](http://www.pnas.org/content/111/21/7713.abstract). Genetic degeneration of old and young Y chromosomes in the flowering plant Rumex hastatulus.

### October 2014

##### Fri. Oct 31, 2014

[Schiffels & Durbin](http://www.nature.com/ng/journal/v46/n8/pdf/ng.3015.pdf). Inferring human population size and separation history from multiple genome sequences.

##### Fri. Oct 24, 2014

[Caicedo et al. 2007](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.0030163). Genome-Wide Patterns of Nucleotide Polymorphism in Domesticated Rice

##### Fri. Oct. 17, 2014

[Crawford et al. preprint](http://biorxiv.org/content/biorxiv/early/2014/10/01/009837.full.pdf) Reticulate speciation and adaptive introgression in the Anopheles gambiae species complex

##### Fri. Oct. 10, 2014

[Martin et al preprint](http://biorxiv.org/content/early/2014/08/20/001347). Evaluating the use of ABBA-BABA statistics to locate introgressed loci.


##### Fri. Oct. 3, 2014

[Huber et al. 2014](http://www.ncbi.nlm.nih.gov/pubmed/25158800) Keeping it Local: Evidence for Positive Selection in Swedish Arabidopsis thaliana.

### September 2014

##### Fri. Sept. 26, 2014

[Romiguier et al. 2014]( http://www.nature.com/nature/journal/vaop/ncurrent/full/nature13685.html?WT.ec_id=NATURE-20140821 ) Comparative population genomics in animals uncovers the determinants of genetic diversity

##### Fri. Sept. 19, 2014

[Brawand et al. 2014](http://www.nature.com/nature/journal/vaop/ncurrent/full/nature13726.html) The genomic substrate for adaptive radiation in African cichlid fish


##### Fri. Sept 12, 2014

[Spencer et al. 2006](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.0020148) The Influence of Recombination on Human Genetic Diversity

##### Fri. Sept 5, 2014

[Carneiro et al. 2014](http://www.plosgenetics.org/article/info:doi/10.1371/journal.pgen.1003519) The Genomic Architecture of Population Divergence between Subspecies of the European Rabbit.

### August 2014

##### Fri. Aug 30, 2014

[Kelley et al. 2014](http://www.nature.com/ncomms/2014/140812/ncomms5611/full/ncomms5611.html) Compact genome of the Antarctic midge is likely an adaptation to an extreme environment.

##### Fri. Aug 23, 2014

[Wilson et al. 2014 ](http://www.genetics.org/content/early/2014/07/23/genetics.114.165571.abstract). Soft Selective Sweeps in Complex Demographic Scenarios.

##### Fri. Aug 16, 2014

[Comeron 2014](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.1004434). Background Selection as Baseline for Nucleotide Variation across the Drosophila Genome

##### Fri. Aug 9, 2014

[Enard et al. 2014](http://genome.cshlp.org/content/early/2014/05/02/gr.164822.113.full.pdf). Genome-wide signals of positive selection in human evolution

##### Fri. Aug 1, 2014

[Arnegard et al. 2014](http://www.nature.com/nature/journal/v511/n7509/full/nature13301.html). Genetics of ecological divergence during speciation

### July 2014

##### Fri. July 25, 2014

**Special double genome delux!** [Myburg et al. 2014](http://www.nature.com/nature/journal/v510/n7505/full/nature13308.html). The genome of Eucalyptus grandis **and** [Schmutz et al. 2014](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3008.html) A reference genome for common bean and genome-wide analysis of dual domestications

##### Fri. July 18, 2014

[Macadangdang et al. 2014](http://elifesciences.org/content/early/2014/06/17/eLife.02792). Evolution of histone 2A for chromatin compaction in eukaryotes

[blog post](blogs/18072014.html)

##### Fri. July 11, 2014

[Guenther et al](http://www.nature.com/ng/journal/v46/n7/full/ng.2991.html?WT.ec_id=NG-201407) A molecular basis for classic blond hair color in Europeans

##### Fri. July 4, 2014

No R.E.H.A.B. Watch some [fireworks](http://daviswiki.org/July_4th_Fireworks) instead!

### June 2014

##### Fri. June 27, 2014

[Ho and Zhang 2014](http://mbe.oxfordjournals.org/content/31/6/1568). The Genotype–Phenotype Map of Yeast Complex Traits: Basic Parameters and the Role of Natural Selection

##### Fri. June 20, 2014

[Yeaman 2013](http://www.pnas.org/content/110/19/E1743.full?sid=bfb4a537-ab08-4c97-811f-cd0b63ba9e9a). Genomic rearrangements and the evolution of clusters of locally adaptive loci

[blog post](blogs/20062014.html)

##### Fri. June 13, 2014

[Chari and Dworkin 2013](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.1003661). The Conditional Nature of Genetic Interactions: The Consequences of Wild-Type Backgrounds on Mutational Interactions in a Genome-Wide Modifier Screen

[blog post](blogs/13062014.html)

##### Fri. June 6, 2014

[Balick et al. preprint](http://biorxiv.org/content/biorxiv/early/2014/03/21/003491.full.pdf). Response to a population bottleneck can be used to infer recessive selection

### May 2014

##### Fri. May 30, 2014

[Nadeau et al. 2014](http://genome.cshlp.org/content/early/2014/05/13/gr.169292.113.abstract). Population genomics of parallel hybrid zones in the mimetic butterflies, H. melpomene and H. erato

[blog post](blogs/30052014.html)

##### Fri. May 23, 2014

[Soria-Carrasco et al. 2014](http://www.sciencemag.org/content/344/6185/738.abstract). Stick Insect Genomes Reveal Natural Selection’s Role in Parallel Speciation

[blog post](blogs/23052014.html)

##### Fri. May 16, 2014

[Rogers et al. 2014](http://arxiv.org/abs/1405.0518). Tandem duplications and the limits of natural selection in Drosophila yakuba and Drosophila simulans

[blog post](blogs/16052014.html)

##### Fri. May 9, 2014

[Hawkins et al. 2014](http://onlinelibrary.wiley.com/doi/10.1111/tpj.12537/abstract). Variation in allelic expression associated with a recombination hotspot in Zea mays

[blog post](blogs/09052014.html)

##### Fri. May 2, 2014 (JRI)

[Do et al. 2014](http://arxiv.org/abs/1402.4896). No evidence that natural selection has been less effective at removing deleterious mutations in Europeans than in West Africans

### April 2014

##### Fri. April 25, 2014 (VB)

[Li 2014](http://arxiv.org/abs/1404.0929). Towards Better Understanding of Artifacts in Variant Calling from High-Coverage Samples.

\emph{Also see [slides](http://lyonlab.cshl.edu/Journal%20Club/JC20140407.pdf)}

##### Fri. April 18, 2014 (JRI)

[Nabholz et al. 2014](http://onlinelibrary.wiley.com/doi/10.1111/mec.12738/abstract). Transcriptome population genomics reveals severe bottleneck and domestication cost in the African rice (O. glaberrima)

*JRI's review (molecol.tex) available in Lab Share folder on Dropbox*

##### Fri. April 11, 2014 (JRI)

NO R.E.H.A.B.  Check out the [Plant Breeding Symposium](http://plantbreeding2014.ucdavis.edu) instead!

##### Fri. April 4, 2014 (JRI)

[Campos et al. 2014](http://mbe.oxfordjournals.org/content/31/4/1010). The Relation between Recombination Rate and Patterns of Molecular Evolution and Variation in Drosophila melanogaster.

### March 2014

##### Fri Mar. 28 2014 (JRI)

[Hirsch et al. 2014](http://www.ncbi.nlm.nih.gov/pubmed/24488960). Insights into the maize pan-genome and pan-transcriptome.

##### Fri Mar. 21 2014 (SM)

[Piepho and Möhring 2007](http://www.genetics.org/content/177/3/1881). Computing Heritability and Selection Response From Unbalanced Plant Breeding Trials

##### Fri Mar. 14 2014 (DV)

[Cortijo et al](http://www.sciencemag.org/content/343/6175/1145.abstract). Mapping the Epigenetic Basis of Complex Traits

##### Fri Mar. 7 2014 (SM)

[Peiffer et al. 2014](http://www.genetics.org/content/early/2014/02/06/genetics.113.159152.full.pdf). The genetic architecture of maize height

### February 2014

##### Fri Feb. 28 2014 (MS)

[Cavrak et al. 2014](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.1004115). How a Retrotransposon Exploits the Plant's Heat Stress Response for Its Activation

##### Fri Feb. 21 2014 (PB)

[Elhaik et al. 2014](http://www.nature.com/ejhg/journal/vaop/ncurrent/abs/ejhg2013303a.html). The ‘extremely ancient’ chromosome that isn’t: a forensic bioinformatic investigation of Albert Perry’s X-degenerate portion of the Y chromosome

##### Fri Feb. 14 2014 (DV)

[Han et al. 2013](http://mbe.oxfordjournals.org/content/early/2013/11/27/molbev.mst229.abstract). Characterizing bias in population genetic inferences from low coverage sequencing data

##### Fri. Feb. 7 2014 (JRI)

[Sankararaman et al. 2014](http://www.nature.com/nature/journal/vaop/ncurrent/pdf/nature12961.pdf). The genomic landscape of Neanderthal ancestry in present-day humans

### January 2014

##### Fri. Jan 31 2014 (VB)

[Nadachowska-Brzyska et al.](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.1003942?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+plosgenetics%2FNewArticles+%28PLOS+Genetics+-+New+Articles%29). Demographic Divergence History of Pied Flycatcher and Collared Flycatcher Inferred from Whole-Genome Re-sequencing Data

##### Fri. Jan 24 2014 (VB)

[Scally et al. 2012](http://www.nature.com/nature/journal/v483/n7388/full/nature10842.html%3FWT.ec_id%3DNATURE-20120308). Insights into hominid evolution from the gorilla genome sequence

##### Fri Jan. 17 2014 (JRI)

[Chapman et al. 2013](http://mbe.oxfordjournals.org/content/30/12/2553). Genomic Divergence during Speciation Driven by Adaptation to Altitude

##### Fri Jan. 3 2014 (AO)

\<CANCELED\> -- There's a first time for everything. (Translation: "CANCELLED" for our British and Canadian friends)

##### Fri Jan. 3 2014 (AO)

[Karhunen et al. 2013](http://onlinelibrary.wiley.com/doi/10.1111/evo.12268/abstract). Bringing habitat information into statistical tests of local adaptation in quantitative traits: a case study of nine-spined sticklebacks.

## 2013

### December 2013

##### Fri Dec. 20 2013 (DV)

[Rettelbach et al. 2013](http://www.jstor.org/stable/full/10.1086/673488). Three modes of adaptive speciation in spatially structured populations

##### Fri Dec. 13 2013 (JRI)

[Korneliussen et al. 2013](http://www.biomedcentral.com/content/pdf/1471-2105-14-289.pdf). Calculation of Tajima's D and other neutrality test statistics from low depth next-generation sequencing data

##### Fri Dec 6 2013 (VB)

[Teng et al. 2013](http://www.sciencedirect.com/science/article/pii/S109727651300748X). Genome-wide Consequences of Deleting Any Single Gene

### November 2013

##### Fri Nov 29 2013

No R.E.H.A.B., but to go along with all your TurkeyDay related activities: [Seidel et al. 2013](http://onlinelibrary.wiley.com/doi/10.1002/jwmg.575/full). Influence of translocations on eastern wild turkey population genetics in Texas

##### Fri Nov 22 2013 (VB,DV)

[Thallmann et al. 2012](http://www.sciencemag.org/content/342/6160/871.full.pdf). Complete Mitochondrial Genomes of Ancient Canids Suggest a European Origin of Domestic Dogs

##### Fri Nov 15 2013 (JRI)

[Kijima and Innan 2013](http://www.genetics.org/content/early/2013/08/26/genetics.113.150292.full.pdf). Population Genetics and Molecular Evolution of DNA Sequences in Transposable Elements. I. A Simulation Framework

##### Fri Nov 08 2013 (JRI)

Review! Pick up hard copy in 262 Robbins.

##### Fri Nov 01 2013 (JRI)

[Lohmueller 2013](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CC4QFjAA&url=http%3A%2F%2Farxiv.org%2Fabs%2F1306.5261&ei=UURzUrfOGqW-igLBtoCAAg&usg=AFQjCNFoh5KxhwcrmuKZP1UM3xQN2xk0ug). The impact of population demography and selection on the genetic architecture of complex traits

### October 2013

##### Fri Oct 25 2013 (OA)

[Parker et al. 2013](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CCkQFjAA&url=http%3A%2F%2Fwww.nature.com%2Fnature%2Fjournal%2Fv502%2Fn7470%2Ffull%2Fnature12511.html&ei=PkRzUpb-NYWdiAKQqYG4CQ&usg=AFQjCNGhGBxb-ICUpfOeut7Iq-CNBcmT0Q&bvm=bv.55819444,d.cGE). Genome-wide signatures of convergent evolution in echolocating mammals

##### Fri Oct 18 2013 (AO,VB)

[Peischl et al. arxiv](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CDAQFjAA&url=http%3A%2F%2Farxiv.org%2Fabs%2F1306.1652&ei=K0RzUozGG6-IigKZq4CoAg&usg=AFQjCNE187lCk7EURsZ_3rWrzNzoVZA0rg&bvm=bv.55819444,d.cGE). On the accumulation of deleterious mutations during range expansions

##### Fri Oct 11 2013 (PMG)

[Ronen et al. 2013](http://www.genetics.org/content/early/2013/06/10/genetics.113.152587). Learning Natural Selection from the Site Frequency Spectrum

##### Fri Oct 04 2013 (JMB)

[Szovenyi et al. 2013](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CCsQFjAA&url=http%3A%2F%2Fmbe.oxfordjournals.org%2Fcontent%2Fearly%2F2013%2F05%2F17%2Fmolbev.mst095&ei=y0NzUq3YJ-GgjAK264CICA&usg=AFQjCNFixSoYD_TS-4tXJ8HmXdF6noaCew&bvm=bv.55819444,d.cGE). Selection Is No More Efficient in Haploid than in Diploid Life Stages of an Angiosperm and a Moss
