---
title: "TE Papers"
output: html_document
---

<!-- still some problems, brachypodium -->
<!-- https://academic.oup.com/gbe/article/10/1/304/4769669 -->


## General TE biology
* [Long-term evolution of transposable elements](https://www.pnas.org/content/104/49/19375)  
* [On the Population Dynamics of Junk: A Review on the Population Genomics of Transposable Elements](https://www.mdpi.com/2073-4425/10/6/419)  
* [Ten things you should know about transposable elements](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1577-z)  
* [How important are transposons for plant evolution?](https://www.nature.com/articles/nrg3374)  
* [Sure Facts, Speculations, and Open Questions About the Evolution of Transposable Element Copy Number](https://pubmed.ncbi.nlm.nih.gov/10952206/)  
* [The Selfishness of Law-Abiding Genes](https://www.cell.com/trends/genetics/fulltext/S0168-9525(19)30191-X#)  
* [A triptych of the evolution of plant transposable elements](https://www.cell.com/trends/plant-science/fulltext/S1360-1385(10)00096-8?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1360138510000968%3Fshowall%3Dtrue)  
* [Do Plants Have a One-Way Ticket to Genomic Obesity?](http://www.plantcell.org/content/9/9/1509.long)    
* [Transposable Elements, Epigenetics, and Genome Evolution](https://science.sciencemag.org/content/338/6108/758.long)   

## TE Popgen
* [The population dynamics of transposable elements](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/B3815EB0AE7CDB71B27FDAE08A282B8A/S0016672300021455a.pdf/population_dynamics_of_transposable_elements.pdf)
* [Epigenetic Silencing of Transposable Elements: A Trade-Off Between Reduced Transposition and Deleterious Effects on Neighboring Gene Expression](https://pubmed.ncbi.nlm.nih.gov/19478138/) 

## Maize TEs  

#### 2020  

* [Gene capture by transposable elements leads to epigenetic conflict in maize](https://www.biorxiv.org/content/10.1101/777037v2)  
* [Genetic and epigenetic contributions to variation in transposable element expression responses to abiotic stress in maize](https://www.biorxiv.org/content/10.1101/2020.08.26.268102v1)  
* [The Genomic Ecosystem of Transposable Elements in Maize](https://www.biorxiv.org/content/10.1101/559922v1)   
* [Cis-regulatory elements within TEs can influence expression of nearby maize genes](https://www.biorxiv.org/content/10.1101/2020.05.20.107169v1.abstract)  

#### 2019  

* [Hybrid Decay: A Transgenerational Epigenetic Decline in Vigor and Viability Triggered in Backcross Populations of Teosinte with Maize](https://www.genetics.org/content/213/1/143)  
* [The genome-wide dynamics of purging during selfing in maize](https://www.nature.com/articles/s41477-019-0508-7?draft=marketing)  
* [Dynamic Patterns of Transcript Abundance of Transposable Element Families in Maize](https://www.g3journal.org/content/9/11/3673)  
* [Monitoring the interplay between transposable element families and DNA methylation in maize](https://journals.plos.org/plosgenetics/article/comments?id=10.1371/journal.pgen.1008291)  
* [Transposable elements contribute to dynamic genome content in maize](https://onlinelibrary.wiley.com/doi/full/10.1111/tpj.14489)  
* [Widespread long-range cis-regulatory elements in the maize genome](https://www.nature.com/articles/s41477-019-0547-0)  
* [Spontaneous mutations in maize pollen are frequent in some lines and arise mainly from retrotranspositions and deletions](https://www.pnas.org/content/116/22/10734.abstract)  

#### 2018  

* [The maize W22 genome provides a foundation for functional genomics and transposon biology](https://www.nature.com/articles/s41588-018-0158-0)  
* [Parallel altitudinal clines reveal trends in adaptive evolution of genome size in Zea mays](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007162)  

#### 2017  

* [Genome-wide mapping of transcriptional enhancer candidates using DNA and chromatin features in maize](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1273-4)  
* [Improved maize reference genome with single-molecule technologies](https://www.nature.com/articles/nature22971)  

#### 2016  

* [Open chromatin reveals the functional maize genome](https://www.pnas.org/content/113/22/E3177)  

#### 2015  

* [Transposable Elements Contribute to Activation of Maize Genes in Response to Abiotic Stress](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4287451/)  

#### Earlier  

* [Remarkable variation in maize genome structure inferred from haplotype diversity at the bz locus](https://www.pnas.org/content/103/47/17644)  


## Other Empirical Systems   

#### Drosophila  
* [Population Genomics of Transposable Elements in Drosophila](https://www.annualreviews.org/doi/10.1146/annurev-genet-120213-092359)  
* [Recent LTR retrotransposon insertion contrasts with waves of non-LTR insertion since speciation in Drosophila melanogaster](https://www.pnas.org/content/104/27/11340)  
* [The population genetics of Drosophila transposable elements](https://www.annualreviews.org/doi/abs/10.1146/annurev.ge.23.120189.001343)  

#### Arabidopsis  
* [The Arabidopsis thaliana mobilome and its impact at the species level](https://elifesciences.org/articles/15716)
* [Population scale mapping of transposable element diversity reveals links to gene regulation and epigenomic variation](https://elifesciences.org/articles/20777)
* [Effects of Recombination Rate and Gene Density on Transposable Element Distributions in Arabidopsis thaliana](https://genome.cshlp.org/content/13/8/1897.long)