---
title: "Some fun inbreeding depression (ID) results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Jim Holland shows maize has higher ID than teosinte

*Image omitted in this repo-local render (missing local file: `id_jim.jpg`).*

We thought this odd, because we showed w/ GERP ([Wang 2017](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1346-4)) that teo has more segregating deleterious sites than maize (panel c). Maize does have higher total load (panel a), but we interpreted that as being due to the big change in the number of fixed deleterious sites.

*External figure omitted in this offline render (Springer-hosted image URL).*

In this light, Jim’s result seemed weird, since del. sites fixed in maize can’t contribute to ID in maize (measured as self vs outcross progeny).

Today we ([Markus Stetter](https://cropevolution.org)) looked at GERP in the parents of Jim's pops, focusing only on segregating sites.  We see the same pattern as before for number of deleterious sites:

*Figure omitted in this repo-local render (missing local file: `gerp_sites.pdf`).*

But here, looking only at segregating deleterious alleles within each taxa, we still see higher load in maize!

*Figure omitted in this repo-local render (missing local file: `mean_total_load.pdf`).*

One explanation is higher selfing/inbreeding in maize, such that each maize individual is more likely to be homozygous for a given allele. But Jim looked at that, and NOPE:

*Figure omitted in this repo-local render (missing local file: `fmaizeteo.jpg`).*

The only other explanation is a right-shifted SFS, such that any given deleterious allele is at higher frequencies in maize. Sure enough:

*Figure omitted in this repo-local render (missing local file: `DAFmaizeteo.png`).*

Which, in [retrospect](https://www.nature.com/articles/nplants201684), should have been obvious from Tajima's D in genes and out (left is maize, right is teo):

*External figure omitted in this offline render (Springer-hosted image URL).*

The difference in D in GERP-rich genic regions is much bigger than outside of genes, suggesting a right skew in the SFS.

**So increased ID in maize is due to lots of weakly deleterious alleles having been bumped up to higher alleele freq.**
